### ISSUE TITLE
White screen on Youtube with skip ad button 

### ISSUE THREAD

**Issue by 1chan-level-journalist** [gorhill/uBlock-for-firefox-legacy#277] opened 2020-11-14 17:21 UTC
### Prerequisites

- [x] I verified that this is not a filter issue
    - Filter issues MUST be reported at [filter issue tracker](https://github.com/uBlockOrigin/uAssets/issues)
    
- [x] This is not a support issue or a question
    - Support issues and questions are handled at [/r/uBlockOrigin](https://old.reddit.com/r/uBlockOrigin/)
    
- [x] I performed a cursory search of the issue tracker to avoid opening a duplicate issue
    - Your issue may already be reported.
- I tried to reproduce the issue when...
    - [ ] uBlock Origin is the only extension
    - [ ] uBlock Origin with default lists/settings
    - [ ] using a new, unmodified browser profile
- [x] I am running the latest version of uBlock Origin
- [x] I checked the [documentation](https://github.com/gorhill/uBlock/wiki) to understand that the issue I report is not a normal behavior

### Description
When watching any random videos, occasionally a white screen loads up with a "Skip Ad" button instead of a video.
Looks like this issue was fixed in the master branch a few days ago, where json-prune scriptlet now comes with the ability to prune all fetch calls.

### A specific URL where the issue occurs

https://www.youtube.com/

### Steps to Reproduce

1. Go to https://www.youtube.com/
2. Start watching any videos
3. Eventually the white screen pops up

### Expected behavior:

Videos display normally with no interruption.

### Actual behavior:

Got flashbanged by an unskippable white screen in the middle of watching videos.

### Your environment

* uBlock Origin version: 1.16.4.26
* Browser Name and version: Pale Moon 28.15.0
* Operating System and version: Windows 7 SP1

**Comment by JustOff** [comment] 2020-11-14 18:21
Duplicate of #272.

**Closed by JustOff** 2020-11-14 18:21 UTC
