### ISSUE TITLE
filtering compatibility ".js"

### ISSUE THREAD

**Issue by AroKol78** [gorhill/uBlock-for-firefox-legacy#284] opened 2020-12-07 19:09 UTC
it is missing in many filters `.js` therefore they do not work
"ubo legacy" still requires `.js`
is it possible to increase the compatibility with "ubo"
my problem example https://github.com/MajkiIT/polish-ads-filter/issues/13818#issuecomment-740037922

did not work `page#@#+js(set-constant, Object.prototype.rekids, undefined)`
it works `page#@#+js(set-constant.js, Object.prototype.rekids, undefined)`

**Comment by krystian3w** [comment] 2020-12-08 08:32
#228

**Comment by hawkeye116477** [comment] 2020-12-08 14:01
https://github.com/gorhill/uBlock-for-firefox-legacy/issues/235#issuecomment-642793690

**Comment by AroKol78** [comment] 2020-12-08 14:30
Manually to change each filter entry is a mordega

**Comment by hawkeye116477** [comment] 2020-12-08 14:53
There is no such a word in English, look at https://pl.bab.la/slownik/polski-angielski/mord%C4%99ga :smile:

**Comment by AroKol78** [comment] 2020-12-08 16:09
it's just my opinion, I know others may have a different opinion
- it is best to transfer the whole "ubo" - fewer problems to the future
it's best to just modify API "manifest.json > install.rdf" and/or something more
something like that "UXP browsers https://github.com/PolishFiltersTeam/PolishCookieConsent"

**Comment by JustOff** [comment] 2020-12-08 16:58
Duplicate of #235.

**Closed by JustOff** 2020-12-08 16:58 UTC

**Comment by AroKol78** [comment] 2020-12-08 19:07
sorry for creating a duplicate - my mistake
I thought that when it's closed https://github.com/gorhill/uBlock-for-firefox-legacy/issues/235 it's no longer a problem
